# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa5fd65fd7e8d29908d21de9a500e74490618d9176d055dd36f63f3db36d72cd7c65b6fe2121ef23508786b061dc4145588722be15cfae49511ae786a2639798

test:
  secret_key_base: 3f63a17e181fd036e2892f4fb7634c2b7bf5338a44eae0b57d09e52a668de2a69b9e9991959e47f1dc20c382f3af0a121830b039111c08f2a45fe75a1371410c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
